const $=id=>document.getElementById(id);
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
let csrf='',pendingQuote=null,poll=null,selectedOrder=null,enabled=false;
async function api(path,body,method){const r=await fetch(path,{method:method||(body?'POST':'GET'),credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},...(body?{body:JSON.stringify(body)}:{})});const v=await r.json();if(!r.ok)throw Error(v.error||'Request failed.');return v;}
function fail(e){$('error').textContent=e.message;$('error').hidden=false;}
function action(fn){return async e=>{e?.preventDefault();$('error').hidden=true;const b=e?.currentTarget;if(b?.tagName==='BUTTON')b.disabled=true;try{await fn(e);}catch(err){fail(err);}finally{if(b?.tagName==='BUTTON')b.disabled=false;}};}
function button(text,fn,cls){const b=node('button',text,cls);b.addEventListener('click',action(fn));return b;}
function plain(html){const doc=new DOMParser().parseFromString(String(html||''),'text/html');return doc.body.textContent||'';}
function facts(entries){const d=node('dl',null,'facts');for(const [key,value]of entries)d.append(node('dt',key),node('dd',value));return d;}
function clearSensitive(){if(poll)clearTimeout(poll);poll=null;pendingQuote=null;selectedOrder=null;for(const id of ['review','order','details','results','orders'])$(id).replaceChildren();}
async function refresh(){const s=await api('/v1/integrations/bitrefill/status');csrf=s.csrf;enabled=s.purchases_enabled;$('connection').textContent=s.connected?'Connected · payment stays in your control':'Connect securely through Bitrefill. No API key to copy.';$('connect').hidden=s.connected;$('disconnect').hidden=!s.connected;$('catalog').hidden=!s.connected;$('history').hidden=!s.connected;if(s.test_provider){$('notice').hidden=false;$('notice').textContent='TEST PROVIDER — simulated invoices and delivery, no real Bitrefill purchase.';}if(!s.purchases_enabled){$('notice').hidden=false;$('notice').textContent='Catalog and review are available. Invoice creation is disabled until this server is enabled for the pilot.';}if(s.connected)await history();}
$('connect').addEventListener('click',action(async()=>{const v=await api('/v1/integrations/bitrefill/oauth/start',{});location.assign(v.url);}));
$('disconnect').addEventListener('click',action(async()=>{const r=await api('/v1/integrations/bitrefill',{},'DELETE');clearSensitive();await refresh();if(!r.provider_revoked){$('notice').hidden=false;$('notice').textContent='Disconnected locally. Provider revocation could not be confirmed; revoke Compralo in your Bitrefill account too.';}}));
$('search-form').addEventListener('submit',action(async()=>{clearSensitive();const c=$('country').value.toUpperCase();const v=await api('/v1/bitrefill/search',{query:$('query').value||'*',country:c});for(const p of v.products){const card=node('article');card.append(node('h3',p.name),node('p',p.countries.join(' · ')),button('View packages',()=>showDetails(p.id,c)));$('results').append(card);}if(!v.products.length)$('results').append(node('p','No matching gift cards for this country. Try another search.'));}));
async function showDetails(id,country){const d=await api('/v1/bitrefill/products/'+encodeURIComponent(id));const root=$('details');root.hidden=false;root.replaceChildren(node('h2',d.name));const select=node('select');for(const p of d.packages||[]){const price=Number(p.payment_price);if(p.payment_currency!=='EUR'||!Number.isFinite(price)||price<=0||price>10)continue;const o=node('option',`${p.package_value} ${p.package_currency||d.currency} gift card · €${price.toFixed(2)} catalog price`);o.value=p.package_value;select.append(o);}const label=node('label','Choose a package');label.append(select);root.append(label);const restrictions=node('details');restrictions.append(node('summary','Redemption instructions and restrictions'),node('p',plain(d.restrictions)),node('p',plain(d.instructions)));root.append(restrictions);const b=button('Review request',async()=>{pendingQuote=await api('/v1/bitrefill/quotes',{product_id:id,package_value:select.value,country});review(pendingQuote);});b.disabled=!select.options.length;root.append(b);root.scrollIntoView({behavior:'smooth'});}
function review(v){const q=v.quote;const root=$('review');root.hidden=false;root.replaceChildren(node('h2','Review your gift card request'),facts([['Product',q.name],['Product ID',q.product_id],['Gift card / quantity',`${q.face_value} ${q.face_currency} · 1`],['Country',q.country],['Recipient',q.recipient],['Catalog estimate',`€${(q.catalog_total_minor/100).toFixed(2)}`],['Payment',`${q.payment_method} · ${q.payment_network}`],['Exact total / fees','Shown on Bitrefill before your wallet payment'],['Approval expires',new Date(v.expires_at*1000).toLocaleTimeString()]]),node('p',q.warning,'notice'));
const terms=node('details');terms.append(node('summary','Gift card terms and redemption'),node('p',plain(q.restrictions)),node('p',plain(q.instructions)));root.append(terms);
const label=node('label',null,'check'),check=node('input');check.type='checkbox';label.append(check,node('span','I reviewed the retailer, country, denomination and redemption restrictions. I approve buying this gift card separately from any physical product. I understand this may be non-refundable and I must approve the final price on Bitrefill.'));root.append(label);
const go=button('Approve and create payment request',async()=>{if(!check.checked)throw Error('Please acknowledge the purchase details.');await api(`/v1/bitrefill/quotes/${v.quote_id}/approve`,{quote_hash:v.quote_hash,acknowledged:true});go.disabled=true;const result=await api(`/v1/bitrefill/quotes/${v.quote_id}/purchase`,{});pendingQuote=null;root.hidden=true;await displayOrder(result);await history();});go.disabled=true;check.addEventListener('change',()=>go.disabled=!check.checked||!enabled);const actions=node('div',null,'actions');actions.append(go,button('Cancel',async()=>{await api(`/v1/bitrefill/quotes/${v.quote_id}/cancel`,{});root.hidden=true;pendingQuote=null;},'secondary'));root.append(actions);root.scrollIntoView({behavior:'smooth'});}
async function history(){const v=await api('/v1/bitrefill/orders');$('orders').replaceChildren();for(const o of v.orders){const b=button(`${o.quote.name} · ${o.status.replaceAll('_',' ')}`,()=>loadOrder(o.order_id),'secondary');b.dataset.orderId=o.order_id;$('orders').append(b);}}
async function loadOrder(id){if(poll)clearTimeout(poll);await displayOrder(await api('/v1/bitrefill/orders/'+id));}
async function displayOrder(o){const shouldScroll=selectedOrder!==o.order_id;selectedOrder=o.order_id;for(const b of $('orders').children)if(b.dataset.orderId===o.order_id)b.textContent=`${o.quote.name} · ${o.status.replaceAll('_',' ')}`;const root=$('order');root.hidden=false;root.replaceChildren(node('h2',o.status.replaceAll('_',' ')),facts([['Product',o.quote.name],['Request',o.order_id],['Invoice',o.invoice_id||'Not confirmed'],['Provider status',o.provider_status||'Awaiting provider response']]));
if(o.status==='reconciliation_required')root.append(node('p','The result needs reconciliation. Do not create another request or pay twice. Check your Bitrefill account or contact support with this reference.','notice'));
if(o.payment_link&&o.status==='awaiting_payment'){const a=node('a','Review exact total and pay on Bitrefill','button');const u=new URL(o.payment_link);if(u.protocol==='https:'&&(u.hostname==='bitrefill.com'||u.hostname.endsWith('.bitrefill.com'))){a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';root.append(a,node('p','Payment is a separate action you complete in Bitrefill / your wallet. The catalog amount was an estimate.','muted'));}}
if(o.delivery_available){const secret=node('pre','Delivery is masked. Reveal only when ready.');const reveal=button('Reveal delivery',async()=>{const d=await api(`/v1/bitrefill/orders/${o.order_id}/reveal`,{});secret.textContent=d.delivery.map(item=>deliveryText(item)).join('\n\n');const copy=button('Copy delivery',()=>navigator.clipboard.writeText(secret.textContent),'secondary');root.append(copy);setTimeout(()=>{secret.textContent='Delivery hidden again.';copy.remove();},60000);});root.append(reveal,secret);}
const list=node('ol',null,'timeline');for(const e of o.events||[])list.append(node('li',new Date(e.at*1000).toLocaleTimeString()+' · '+e.kind.replaceAll('_',' ')));root.append(list,button('Refresh status',()=>loadOrder(o.order_id),'secondary'));if(poll)clearTimeout(poll);
if(['awaiting_payment','payment_pending'].includes(o.status)){poll=setTimeout(()=>loadOrder(o.order_id).catch(fail),15000);}if(shouldScroll)root.scrollIntoView({behavior:'smooth'});}

function deliveryText(value,prefix=''){
 if(value==null)return '';
 if(typeof value!=='object')return prefix+String(value);
 const names={redemption_info:'Gift card redemption',status:'Delivery status'};
 return Object.entries(value).filter(([,v])=>v!=null).map(([k,v])=>deliveryText(v,(names[k]||k.replaceAll('_',' '))+': ')).join('\n');
}
window.addEventListener('pagehide',clearSensitive);refresh().catch(fail);
